import java.util.ArrayList;
import java.util.Arrays;

public class MovieDatabase {
	
	public ArrayList<Movie> getMovieArrayList() {
		ArrayList<Movie> movieArrayList = new ArrayList<>();
		
		for (int i = 1; i < 7; i++) {
			movieArrayList.add(getMovie(i));
		}
		
		return movieArrayList;
	}

	public Movie getMovie(int movieChoice) {
		switch (movieChoice) {
		case 1:
			String tl0001 = "Pulp Fiction";
			int rt0001 = 154;
			ArrayList<String> sc0001 = new ArrayList<>(Arrays.asList(
					"Late one morning in the Hawthorne Grill, a restaurant on Sunset Boulevard in Los Angeles, a young couple, Honey Bunny (Amanda Plummer) and Pumpkin (Tim Roth), discuss the pros and cons of robbing banks versus liquor stores. Then they add restaurants to the equation, realizing they can make more by taking customers' wallets than they get out of the till. The two kiss, declare they love each other and stand up in their booth, announcing that they're robbing the diner.",
					"Earlier in the day, Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) arrive at a San Fernando Valley apartment building. They are hit men in the employ of Marsellus Wallace and have come to retrieve a valuable belonging of Wallace's from a group of would-be crooks led by a young and naive guy named Brett (Frank Whaley). They take back the valuable item -- kept in a briefcase, it glows warmly and transfixes whoever looks at it. Jules recites what he claims is a Bible verse, Ezekiel 25:17, before he and Vincent execute Brett.",
					"At his strip club, Marsellus Wallace (Ving Rhames) pays boxer Butch Coolidge (Bruce Willis) to throw his next fight. Jules and Vincent arrive; though it's only a few hours after their visit to the Valley, the two hit men are sporting gym clothes in place of the suits they wore earlier in the day. While Jules heads to the men's room, Vincent goes to the bar and encounters Butch. The men take an instant disliking to each other. Vincent insults Butch but before Butch can retaliate, Marsellus calls Vincent over and embraces him. Marsellus is leaving town that evening and Vincent is to take Marsellus' wife, Mia (Uma Thurman), out for dinner to keep her entertained. Rumors abound that Marsellus gravely wounded another associate, Antoine, who he believed had been improperly friendly with Mia, so Vincent is nervous.", 
					"Before picking Mia up, he visits his drug dealer, Lance (Eric Stoltz), and buys some high-quality heroin. Properly sedated, he escorts the cocaine-addicted, chain-smoking Mia to Jack Rabbit Slim's, a West Hollywood 1950s-themed restaurant. After some small talk about European travel, Mia's failed acting career, foot massage, and the rumors about Antoine (which Mia dispels), Mia enters herself and Vincent in a dance contest. They dance The Twist and win a trophy. After dinner, they return to the Wallace's home. Vincent goes to the bathroom to talk himself out of making a pass at Mia. Meanwhile, she discovers the baggie of heroin in his coat pocket and, assuming it's cocaine, snorts some. She immediately passes out and begins to foam at the mouth. Panicked, Vincent takes the dying Mia to Lance's where they argue about what to do with her. Following Lance's advice, Vincent is able to revive her with a shot of adrenaline administered straight to the heart. Vincent takes Mia home. They agree not to tell Marsellus what happened since both of them would get in trouble for it.",
					"The following night, before his fight, Butch dreams of an incident from his childhood: Back at his Tennessee home in 1973, Captain Koons (Christopher Walken) visited Butch to bring him a gold watch. The watch had belonged to Butch's great-grandfather, who took it to World War I with him. Butch's grandfather had taken it to World War II, and Butch's father to Vietnam. Butch's father died as a POW, but gave the watch to Koons to return to Butch. Koons says that he and Butch's father had to hide the watch in their rectums to keep it away from their captors. Butch reaches up with his hand and takes the watch from Koons.",
					"Butch wakes from the dream. Instead of throwing the match (offscreen), he fights so viciously that he kills his opponent. He took Marsellus' money and bet it on himself; his winnings will amount to a small fortune. Butch makes small talk with Esmarelda (Angela Jones), the driver of the cab he is in, who reveals that she knows he's the boxer who killed his opponent; she seems fascinated with the topic of death. Esmarelda drives Butch to the seedy motel where he and his French girlfriend, Fabienne (Maria de Medeiros), are staying, having abandoned their apartment. In the morning they will travel to Butch's hometown of Knoxville, Tennessee, claim their winnings, and leave the country. While packing the next morning, however, Fabienne reveals that she forgot the gold watch, the belonging Butch cherishes above all others.", 
					"After a savage outburst in which he wrecks the motel room's television, Butch takes Fabienne's car to get the watch, parking a few blocks away and walking through a vacant lot to his apartment building as a precaution. He enters without incident and finds his wristwatch in the bedroom. He realizes he's not alone in the apartment when he notices a sub-machine gun in the kitchen. Catching Vincent off guard as he emerges from the bathroom, Butch kills him with the gun he found. He leaves his apartment after wiping the gun down with a tissue to remove his fingerprints.",
					"Leaving the apartment with his watch, Butch encounters Marsellus crossing the street. He tries to run Marsellus over with his car but only wounds him and is hit by another car himself. Both are injured and Marsellus chases Butch into a pawn shop. There, the owner, Maynard (Duane Whitaker), overpowers them. Marsellus and Butch wake up in the basement of the pawn shop, bound and gagged. Maynard has called his cousin Zed (Peter Greene), who works as a security guard. Maynard and Zed are apparently a pair of redneck serial killers who kill passersby who happen into their store. While the Gimp (Stephen Hibbert), a huge man-child dressed head to toe in black leather fetish gear, watches Butch, Maynard and Zed take Marsellus into the next room and begin to rape him.", 
					"Butch manages to break the ropes and chair holding him and knocks out the Gimp. Ready to leave the pawn shop and Marsellus to his fate, Butch has an attack of conscience and procures a samurai sword and rescues Marsellus; in the process, Maynard is killed and Zed emasculated by a shotgun blast fired by Marsellus. Marsellus stays behind to oversee the torture-execution of Zed (\"I'ma get medieval on your ass,\" he tells him), but promises that as long as Butch never mentions what happened and never returns to Los Angeles, Marsellus will forget that Butch betrayed him in the boxing ring. Butch agrees. In the final scene, Butch and Fabienne leave town on Grace, Zed's chopper-style motorcycle.",
					"Three days earlier, flashing back in time to just after Vincent and Jules finish killing Brett for stealing Marsellus' prized possession, a gang member (Alexis Arquette) they had not known about bursts out of the bathroom where he had apparently been when Jules and Vincent entered and empties a large pistol point blank at them. However, all of the bullets miss Vincent and Jules, hitting the wall behind them, so they return fire and kill the gang member. Jules is certain what occurred was divine intervention, but Vincent dismisses the idea. They leave with Marvin (Phil LaMarr), Marsellus' inside man in the gang. In the car, Jules continues his insistence that what happened in the apartment was a miracle and that he's retiring from Marsellus' gang.", 
					"Vincent leans over the front seat, asking Marvin if he believes in miracles, but accidentally shoots him in the head and kills him. The inside of the car is now covered in blood and brain matter. Jules, furious at Vincent's klutziness, drives to the house of his only friend in the Valley, a former colleague named Jimmie (Quentin Tarantino). Jimmie lets them hide the car in his garage but angrily tells them that they have to get rid of the body within an hour -- before his wife Bonnie comes home from her night shift at a hospital. Jules calls Marsellus at his home to explain their predicament. Marsellus then calls Winston Wolf (Harvey Keitel), a suave and professional \"cleaner\" who solves problems. Wolf arrives at Jimmie's house and tells Vincent and Jules how to clean up the car and themselves -- they have to strip out of their business suits, be sprayed down with a garden hose and wear Jimmie's spare T-shirts and shorts (which explains their attire at the strip club) -- then helps them dispose of the car and body at a junkyard belonging to a discreet friend named Monster Joe, whose daughter is Mr. Wolf's girlfriend.",
					"With the whole situation resolved, Jules and Vincent decide to have breakfast at the Hawthorne Grill, where they continue their discussion about miracles. Jules reveals his plan to leave his criminal life and travel the globe as a mendicant, helping those suffering under tyranny. Vincent, upset that his friend and partner is leaving the life, mocks him, then goes to the bathroom. Just then Honey Bunny and Pumpkin (from the prologue) begin their robbery of the diner. They furiously collect the cash from the register and the patrons' wallets.", 
					"Jules gives Pumpkin his wallet, but when Pumpkin tries to take Marsellus' briefcase, Jules pulls his gun and disarms Pumpkin. While Vincent holds Honey Bunny at bay, Jules explains to Pumpkin how, even earlier that morning, he would have killed Pumpkin and Honey Bunny without a second thought. He recites his ersatz version of Ezekiel 25:17 again: \"The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who in the name of charity and good will shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who attempt to poison and destroy my brothers. And you will know my name is the Lord when I lay my vengeance upon you.\"",
					"Jules explains that while he previously thought it was cool to make such a cold-blooded passage the last thing his victims heard, he now realizes that the \"tyranny of evil men\" part of the passage refers to him, and he intends to become a better person. He and Vincent allow Honey Bunny and Pumpkin to leave with all the money but not the briefcase. They leave the diner themselves and head to Marsellus' strip club."));
			return new DVD(tl0001, rt0001, sc0001);
			
		case 2:
			String tl0002 = "Eternal Sunshine of the Spotless Mind (Pirated Version)";
			int rt0002 = 108;
			ArrayList<String> sc0002 = new ArrayList<>(Arrays.asList(
					"Joel is at the train station, but rather than take his usual train, he hops over to a different one. From another station he calls in sick.",
					"Joel goes to the beach with his journal, here he notices pages torn out of it. Shrugging it off as nothing he starts up another entry about his ex-girlfriend Naomi. Clementine shows up at the beach.",
					"Clementine walks into a Diner, Joel is already in there. They make eye contact, but little else.",
					"Both Joel and Clementine are back at the beach, they stare out at the water.",
					"The meet up again at the train station, this time eye contact with little wave thrown in.",
					"On the train, Clementine is the first to break the silence. She does most of the talking, which consists mostly about her hair colours. Joel eventually ends the conversation by claiming he has some writing to get to. Throughout the trip the train car fills up with passengers, Clementine ends up sitting closer and closer to Joel.",
					"On exiting the train station Joel notices a large gash in his car.",
					"Joel is driving, he spots Clementine walking on the sidewalk, he offers her a ride. At first, she declines, but then accepts. At her house she offers drinks to Joel, who like Clementine, at first declines.",
					"Joel is in Clementine’s place, they drink, listen to music, and chat Clementine shares everything and anything with Joel, Joel on the other hand is shy and can’t hold her gaze for very long. He agrees to go to Boston with her. Patrick, her boyfriend, is mentioned.",
					"Joel arrives back at his place, where two guys Patrick and Stan tail him.",
					"Joel is in the entranceway getting his mail, he has blue dots on his head. He runs into another tenant there but Joel quickly dodges a conversation when he sees he has an envelope from Lacuna.",
					"In his apartment, Joel changes into pajamas fresh from the package, and swallow a pink pill from the vile. Paranoid, he rushes to the window and spots the van, he tries to see who is in it, but gives up. In the Van the two guys, Patrick and Stan, watch Jeol leave the window, once the lights to his place go out, they get moving. They retrieve a bunch of large briefcases from the back of the van and make their way to the building.",
					"Stan and Patrick enter Joel’s place.",
					"Joel’s reaction to the pill, he lies down on his bed and gets drowsy, it’s black, we hear Stan and Patrick enter, along with Patrick singing.",
					"Joes is outside the building, he sees the van again along with figures inside, this time one of them waves and laughs. He rushes inside where he bumps into Frank, their conversation from before is repeated, this time Frank fades away.",
					"Joel is at Rob and Carries’ place telling them that he is upset with a relationship and has to be the one to resolve it. He holds a red paper wrapped gift. A shot of the store Antic Attics where Joel selects jewelry and gets it in a red box for Clementine. A heart shaped card reads “Clem — I’m sorry. I love you. Joel.”",
					"Joel arrives where Clementine works to give her the gift but is horrified to discover not only does she not recognize him, but also has a boyfriend. Back at Rob and Carries’ Joel is eventually shown a card which explains that Clementine has had Joel erased from memory and they aren’t supposed to mention this to her.",
					"Joel arrives at the Lacuna offices, outside them he sees double of himself, which almost gets hit by a truck. Inside he meets Mary, who takes him to see Mierzwiak. He explains the situation to Joel of how he shouldn’t have seen this and that Clementine was not happy and wanted to move on.",
					"In the kitchen of Rob and Carries’ home Joel talks with Carrie about this new information while Rob attempts to build a birdhouse whilst puffing on a joint. Carrie suggests this may have been a lark by Clementine.",
					"Joel is in his car at a drive-in movie theatre, crying, fogging up the windows.",
					"Joel storms into Mierzwiak’s office at the Lacuna building demanding that he gets the operation as well. Having some responsibility in all of this Mierzwiak agrees and tells Joel to go home and collect anything that has to do with Clementine. Joel does and returns with two full garbage bags. He almost gets hit by truck like we seen earlier on.",
					"Joel is seated in an examination chair as Stan makes him inspect the items Joel brought. The fading of the room continues, Mierzwiak’s voice is affected too. Suddenly Joel finds himself standing in the room and watches himself in the chair. He is able to copy what Mierzwiak says based off of memory. Then Stan voice comes from somewhere outside the room.",
					"Inside Joel’s apartment, Joel is fast asleep in his bed. A series of electrodes connect his head to machines. Believing that there’s a voltage issue, Stan gets Patrick to check the connections, which seem to help as back in the lab, the memory deteriorates.",
					"Patrick begins criticizing Joel’s place and asks Stan who is better looking out of him and Joel. Stan refuses to answer and tells Patrick to stay focused. Later on, Stan mentions that Mary will be stopping by, which causes Patrick to bring up his “new girlfriend” and goes on to tell Stan that his situation is a little weird, but Stan cuts him off saying they need to focus.",
					"Past Midnight at Joel’s apartment and a drunk Clementine stumbles in, Joel was waiting up for her and he’s not happy. They soon get into an argument causing Clementine to grab a few things and leave. Joel gives chase, he goes outside and notices his car up against a fire hydrant, scratched up.",
					"He hops in and quickly catches up to Clementine. He tries to apologize but she won’t have it. He changes his tone saying by morning she will be gone and he will be happy. She continues on, Joel gets out of the car and pursues her down a street on foot, but once he gets to the end he returned to where he started, back at his own car.",
					"At this point, Patrick continues on about his girlfriend. He tells Stan that not only did he fall in love with Clementine, but also stole a pair of her panties when they were erasing Joel from her memory. In the dream world Joel can her all of this.",
					"Joel has shifted to another scene, him and Clementine are having dinner and watching T.V. Patrick’s voice is still heard, he tells of how he asked Clementine out the day after they worked on her. Joel tells Clementine that a guy stole her panties. The memory fades.",
					"In a different memory, Joel is back in his apartment and acts dead on the floor when he hears Clementine coming down the stairs. She sees him and the only reaction she really gives him is “ I should’ve left you at the flea market”. Joel’s memory jumps to the market where they have a heated argument over having a child. This memory also begins to fade and just before it disappears Joel tells Clementine that all this pain and hurt will be whipped away. She says she’s glad to which Joel responds “ Me, too”",
					"Another memory, this time Joel is at a bar. He returns to his table to find another guy sitting in his spot, flirting it up with Clementine, who soon begins to insult Joel so all the patrons at the bar can hear. As the memory fades a doorbell rings. The bartender looks at Joel and asks him if it’s his doorbell.",
					"Mary has rang the doorbell, Patrick let’s her in with a “hello” she simply walks past him. Seeing the coolers that Stan and Patrick are drinking she goes in the kitchen and returns with a bottle of scotch and 2 glasses for herself and Stan. The conversation quickly goes to Barlett’s and Mierzwiak.",
					"Joel is in bed with Clementine who questions Joel about his lack of communication with her. The memory shifts to a Chinese restaurant. Joel and Clementine are having dinner, the chat is very stale. Clementine slams back the wine and tells Joel to stop leaving hair on the soap. Patrick’s voice spills into the memory. Joel looks around and sees the bookstore scene from earlier. Joel watches from afar, that is until he sees Patrick kiss Clementine. He walks from the restaurant to the bookstore to try and get a look at Patrick but is unable to see his face.",
					"Back in the real world with Stan, Patrick has received a call from Clementine who wants him to come over. Stan says no at first but is convinced by Mary to let him leave. Patrick’s last line “ I’ll be right over, Tangerine. “ triggers a reaction from Joel.",
					"A new memory gradually comes into focus, Clementine is modeling a bright orange sweater for Joel, who calls her a tangerine. Something clicks in Joel’s head just before the memory shifts to Clementine’s apartment. They are both in bed, underneath the blankets. Clementine tells Joel of her favourite story as a kid which gets her emotional. Soon after they begin to make love until the memory starts to fade. Panicked, Joel jumps up and starts yelling out to Mierzwiak to stop the procedure, he has changed his mind.",
					"Stan and Mary are now smoking a joint while watching the monitors. Mary tells Stan about how amazing Mierzwiak’s procedure is and how it’s a gift to the world. Stand asks her if she loves Mierzwiak, she hesitates before denying it.",
					"Patrick arrives at Clementine’s place. She is a mess and appears to be in distress saying nothing makes sense anymore. Suddenly she asks Patrick to go to Boston tonight. Patrick calls Stan who is stoned and is watching an equally as stoned Mary, dance around. He says he can handle things. Patrick rifles around in a bag and retrieves a gift and a letter. The letter was written by Clementine to Joel about the night they went to Boston.",
					"Joel is now in the memory of that night, all is perfect until that memory begins to fade like the other. In an attempt to escape he grabs Clementine’s hand and runs, at first across the river, but then he begins to run through a series of past memories of Clementine. He turns to face her and sees only a woman he doesn’t recognize.",
					"Joel barges into Mierzwiak’s office and sees himself giving the tape recorder session. He demands that Mierzwiak stop this procedure and leave him alone, but Mierzwiak only says he can’t because he is only a part of Joel imagination. Joel spots Patrick in the shadows and charges after him, but never gets any closer.",
					"At Clementine’s place Patrick finishes reading the letter just as Clementine shows up all dressed to go. Patrick hands her the gift, a necklace that she really loves. Back at Joel’s apartment Stan and Mary are having sex on the floor, right next to Joel’s bed.",
					"Clementine and Joel are in the middle of a forest. Joel confesses that he hired people to erase her from his memory and he wants it to stop but can’t cause he’s asleep. Clementine tells him to just wake himself up. He tries, and for a brief moment could see his own ceiling but returns to the forest. Angry he blurts out the only reason he did this was because she did it to him first. The memory starts to fade and is replaced by the sound of rain, Joel spots a window floating in mid-air.",
					"Joel shifts to one of his favorite memories. He and Clementine sit on a couch on a rainy day reading a book together. Clementine tells Joel to take her to a memory she doesn’t belong in to try and escape the eraser people. Joel tries, a series of memory fragments flash by.",
					"Joel lands in a memory from his childhood. He plays underneath the table as his mother talks with a neighbor who is now Clementine. Joel starts crying, he wants his mommy and doesn’t want to lose Clementine, until she points out that this memory isn’t fading.",
					"In the real world this causes all sorts of wrong for Stan. Him and Mary, both fairly stoned, decide to call Mierzwiak. Stan does and soon enough Mierzwiak is on his way, Stan tries to get Mary to leave, but she wants to remain there.",
					"Joel and Clementine make love underneath the table in his mom’s kitchen. Joel tells Clementine that she’s dating a guy named Patrick who is copying Joel and stole her panties. Clementine tells Joel to find her in the morning and tell her everything.",
					"Patrick and Clementine are on route to Boston, Clementine is crying thinking there’s something wrong with her, Patrick tries to soothe her, but this only seems to make it worse.",
					"Stan and Mary wait anxiously for Mierzwiak, Mary more so about how she looks. When he does show up, Mary pounces for the door to let him in. After being told by Mary why she’s there, he hooks up to the system via his own laptop and quickly finds Joel. Back in his mom’s kitchen Joel is being bathed in a large sink, he’s at peace until things vanish and he is left there struggling in a sink for a moment, until he is sent to another memory. One of Clementine and him at a drive-in movie theatre.",
					"Just as Joel realizes what’s going on, Clementine vanishes. In a desperate attempt, he hugs the air and calls out “Tangerine” which pops Clementine back into the memory and confuses Mierzwiak in the real world. They take off on the run Joel looks back and sees that the car has vanished and for a brief moment awakes back up in his apartment. Mierzwiak sedates him again sending back into the memory world, there, Clementine tells him to hide her in “Humiliation”. Mierzwiak believes things are under control now.",
					"Joel forces his memory to go to something humiliating and shift into a black void. In the real world Mierzwiak is just about to leave when Stan tells him they lost Joel again. Joel has now moved on to a memory of him being caught masturbating by his mom. Mierzwiak takes control of the machines and quickly gets Joel back on track. In the dream world Joel is at the beach in the middle of winter. Clementine goes running off towards a house, Joel chases after her and pulls her away as things start vanishing.",
					"Joel is in a memory of him Clementine pretending to suffocate Joel with a pillow. Joel pranks Clementine that he’s actually dead. Joel shifts to a childhood memory where he is forced to hit a dead bird with a hammer by other kids. He does, afterwards Clementine walks him to his childhood home where she says it’s her turn to be suffocated with the pillow. When Joel removes the pillow he discovers that Clementine has disappeared and his childhood home is now crumbling.",
					"Seeing that Mierzwiak has got the hang of finding Joel, Stan decides to go out for a smoke leaving Mary and Mierzwiak alone. The start talking about quotes, Mary tells one that Mierzwiak doesn’t know by Alexander Pope “How happy is the blameless Vestal’s lot! The world forgetting, by the world forgot: Eternal sunshine of the spotless mind! Each prayer accepted, and each wish resigned.” Soon after Mary kisses Mierzwiak, who at first refuses, but eventually gives in.",
					"From the van Stan can see them starting to have sex, a car pulls up to, it’s Mierzwiak’s wife Hollis. Stan honks the horn to warn them, but this only causes them to stand up in full view of Hollis. She is in her car ready to leave when Mierzwiak and Mary show up outside. They both try to tell her it was a mistake and a one-time thing. Hollis tells Mierzwiak to tell Mary the truth and tells Mary “Poor kid. You can have him. You did”. Mierzwiak only tells her that they have a history and she wanted the procedure done, Mary leaves.",
					"Clementine is lying on the ice with Patrick, but something isn’t right. Patrick says exactly what Joel said to her in the letter, this time Clementine cries, gets up, and runs.",
					"Joel is drawing a portrait of Clementine in a skeleton costume, mixed in with this memory is that of his father fishing in a rowboat. He tells Joel to not waste his life or else he’ll be sewn into his own fate. Clementine tells Joel this isn’t true. The memory pops out of existence.",
					"Joel and Clementine are now in a memory of their first date. They sneak into the movies. Clementine quizzes Joel on the particulars of their first date, what they talked about and what she was wearing, he gets them right. Joel drives Clementine home and later on makes love to her in her apartment. The memory fades away.",
					"Mary returns to the Lacuna offices where she searches for her folder. She finds it in Mierzwiak’s desk, in it is the tape recording of her session with Mierzwiak.",
					"Another one of Joel’s memories. This time he goes through his break up with Naomi and his hooking up with Clementine. At the end of the memory Joel is talking with Clementine at the bookstore where she works. Joel says things will be different if they can give it one more go around. She responds with “ Remember me. Try your best. Maybe we can.”",
					"This is it, Joel’s first ever memory of Clementine. At his apartment Joel leaves Naomi behind due to her having some work to get done. Joel travels to a beach bonfire party with Rob and Carrie. There he wanders off on his out and this is when he comes across Clementine. Both Joel and Clementine talk about their true thoughts and feelings that day as the memory plays on.",
					"They walk along the beach together and spot a house, which is soon broken into by Clementine. Joel, infatuated with Clementine at this point, nervously follows her in. This doesn’t last too long as Clementine scouts out the place Joel walks out the front door claiming he has a ride he needs to catch.",
					"This time he stops, he confesses to Clementine that he felt like a scared little kid and that he ran back to the bonfire to outrun his humiliation. Clementine tells him to come back and make up a goodbye this time. He returns to Clementine and as they kiss the memory fades.",
					"Two quick memories of Joel running back to the bonfire and the second of the ride back home with Rob and Carrie.",
					"Stan and Mierzwiak have completed the procedure and begin to clean up. Mierzwiak tries calling his wife, she doesn’t pick up.",
					"Mary is still in Mierzwiak’s office listening to the tape. We learn that she was also pregnant with Mierzwiak’s child, but they decided to get an abortion.",
					"Stan and Mierzwiak are finished cleaning, Stan leaves to return the van back to the Lacuna building.",
					"Patrick and Clementine are driving back from Boston, Clementine is silent and depressed. Patrick tries to start a conversation but fails.",
					"Stan returns to the Lacuna building where he sees Mary carrying a box of her belongings to her car, she is leaving Lacuna. She asks Stan if he knew or even suspected that her and Mierzwiak were together. Stan replies he only seen them together once, but they looked happy and in love. Mary goes to her car and places her box in the trunk, which of filled with many boxes of Lacuna files.",
					"Joel performs his regular routine after waking up. Outside he finds the scratch on his car but doesn’t know how it happened. He drives to the train station where he catches his train to work.",
					"Mary listens to her own recording as she drives, she cries. The back of her car is also filled with boxes of files.",
					"Joel, at work, calls Naomi and schedules a dinner for later that night",
					"Mary is in her apartment with Mierzwiak, she tells him she doesn’t like what he does to people. Mierzwiak says he needs the files back but Mary denies him claiming them for her own.",
					"Joel and Naomi walk down a street. Both say they missed each other. Joel tells her he hasn’t been seeing anyone for two years whereas Naomi mentions she’s met a good guy. Naomi ends up kissing Joel anyways.",
					"Clementine is back in her apartment and is crying on her bed. Patrick is by a window flipping through Joel’s journal for tips.",
					"The same scene from the start, Joel ditches work and goes to another train at the station.",
					"Joel leaves Clementine’s apartment and says he will call her that night. He returns to his own place where Naomi calls. She says she had a nice time with him the other night and seems to be interested in getting back together, Joel doesn’t think they should rush it. After the call with Naomi ends he calls Clementine, soon they set up a date for the next night.",
					"Joel’s and Clementine’s date on the frozen Boston river. Clementine rushes out on it with no care in the world and Joel hesitates, too scared. He submits to Clementine’s pleas and joins her. There they lie side by side, snuggle up, and point out the constellations they know.",
					"Joel pulls up to Clementine’s place to drop her off, but Clementine wants to go to his place. She runs inside to gather her toothbrush a small bag of things. On her answer machine we hear Patrick’s voice, he’s worried about her and wonders where she is, and that he’ll stop by in the morning to check on her. Outside Patrick shows up to the house but walks away briefly when he sees Joel. Next moment he is at the driver’s side window asking why Joel is there, but soon cowards out and just asks Joel for a smoke before walking away.",
					"Clementine returns from her place and they take off. They don’t get far when Clementine discovers the Lacuna envelope she got in the mail. She takes out the tape and plays in through the car’s stereo system. The tape is of her session with Mierzwiak about Joel, she insults him and tells of all her dislikes about him. This causes Joel to reverse back and leave a crying Clementine back outside of her apartment. Patrick is still outside and rushes up to Clementine who screams at him to get away.",
					"Later on Clementine is in her car driving to Joel’s using a torn-out piece of phonebook with his address circled on it.",
					"Approaching Joel’s apartment building, Clementine runs into Frank, who knows her but she has no idea who he is.",
					"Clementine arrives outside Joel’s door and sees that it’s open. she hears Joel’s voice and goes inside; the place is a mess. She finds Joel sitting down listening to his own recording. They apologize to one another while Joel’s recording plays on. Things start to work out until Joel returns with a couple glasses of what little scotch Mary left them. At this point, on the recording, Joel mentions that he believes someday Clementine will just go around screwing everyone, this upsets her and soon after she leaves.",
					"Joel catches up to her down the hall and tells her to wait for a moment. Clementine tells Joel how they will end up, that he will find things to dislike about her and her feeling bored and trapped with him … to which Joel replies … “Okay”."));
			return new DVD(tl0002, rt0002, sc0002);
			
		case 3:
			String tl0003 = "Spaceballs";
			int rt0003 = 96;
			ArrayList<String> sc0003 = new ArrayList<>(Arrays.asList(
					"The movie opens with a Star Wars-esque text on the screen that informs the viewer of the war between Planet Druidia and Planet Spaceball. Druidia has been at peace for some time now and has managed to stop Planet Spaceball in their tracks by constructing a giant air shield around the planet. Planet Spaceball has been in an air shortage ever since and the numbers are reaching critical levels.",
					"We are shown the outline of an extremely large ship. The end of the ship has a bumper sticker on it that reads \"We brake for nobody!\". Inside we are shown that one of the cadets has contacted Lord Dark Helmet when they've reached Planet Druidia. He then goes over Dark Helmet's Helmet when he informs them that he contacted President Skroob. Lord Helmet is furious, but informs his henchman Col. Sanders their plan once they reach Druidia's atmosphere.",
					"Cut to Planet Druidia. We are shown that Princess Vespa, the daughter of Druish king Roland, is about to get married to a guy named Prince Valium, who has a sleeping disorder. As she approaches the alter, she tells her father that she doesn't love the guy she is about to marry and leaves the wedding. She and her caretaker, a robot named Dot Matrix, escape in the new Mercedes space cruiser that Roland had purchased.",
					"We are then shown the outside of a Winnebago. Inside, the captain - Lonestar, is seen asleep at the wheel while his companion Barf is seen stuffing his face. They then get a call from an associate of ruthless mobster Pizza The Hutt. Pizza tells Lonestar the job he was originally hired to do got screwed up, and now he's owed $1 million spacebucks. And the money has to be paid by a certain time, or else. The next call they get is from King Roland who wants Lonestar and Barf to track down Princess Vespa, but unfortunately he thinks the Spaceballs might have got to her first. They manage to locate the position of her Mercedes space cruiser and rescue her.",
					"Lonestar decides to make quick tracks to escape Spaceball One and Dark Helmet. He puts the Winnebago into hyper active mode and makes quick tracks. Dark Helmet decides to go after them, but to catch up, they put Spaceball One into Ludicrous Speed mode. They overshoot the Winnebago by a week and a half. Just as they're all set to go home, the Winnebago runs out of gas and they crash into a remote desert planet. Lonestar and Vespa get into a huge fight about what they can take with them, Lonestar tells Vespa to take only what you need to survive. Barf informs them that they have to make haste before Spaceball One comes back to make them all dead.",
					"They get lost in the desert and think everything is hopeless. During the night Lonestar and Vespa share a mutual attraction to each other before they're interrupted by Dot's virgin alarm. The next day after walking for hours, it looks like they're goners. But thankfully they're rescued by a group of small people who are followers of the almighty Yogurt.",
					"Back on Spaceball One, Dark Helmet is desperate to locate Vespa as President Skroob informs them they can use her for ransom to get a crack at Druidia's air. So in order to locate exactly where they are, Col. Sanders informs them about a new technology they can use called Instant Video - where they can watch the movie as it's being made. Unfortunately they fast forward too far and are at the \"now\" moment of the movie. They then manage to locate the group on the moon of Vega.",
					"Spaceball One heads to Vega to locate them in the desert. Dark Helmet instructs his minions to literally comb the desert for the foursome. But they're taken to Yogurt's underground lair where he teaches the group about the wonderful world of movie tie-in merchandising. He also teaches Lonestar the power of a magical force in the universe called \"The Schwartz\". Lonestar asks Yogurt about the medallion he wears on his neck. Yogurt tells him that will be later revealed to him at the proper time.",
					"Spaceball One finally arrives in Vega. Dark Helmet decides to trick Vespa into thinking that he's in fact her father King Roland. The trick worked and Lonestar, Dot Matrix, and Barf decide to go after her and destroy Spaceball One in the process. Lonestar is given the Ring Of The Schwartz, as well as a fortune cookie which Yogurt explicitly instructs him to open before eating. He also hands them a can of special liquid schwartz fuel to use if needed.",
					"Back on Planet Spaceball, Dark Helmet has arrived and has presented President Skroob with Princess Vespa, who they will use to scheme King Roland into giving them the combination to Planet Druidia's air shield, destroying Planet Druidia and saving Planet Spaceball. After threatening to give Princess Vespa back her old nose, King Roland agrees to give up the combination. It's 1 - 2 - 3 - 4 - 5. The exact same combination that President Skroob has on his luggage. Skroob orders Spaceball One ready for departure and to have the combination on his luggage changed.",
					"Barf, Lonestar and Dot Matrix finally manage to head to Planet Spaceball, and locate Princess Vespa in a remote prison cell. But to do so requires getting past several heavily armed Spaceballs. They manage to successfully do so. They then high tail it out of the prison and head for Spaceball One.",
					"Spaceball One has managed to successfully penetrate Planet Druidia's air shield. But in order to get the air out, Dark Helmet flips a switch and has Spaceball One transformed into a maid with a giant vacuum cleaner. Lonestar, Barf, Vespa, and Dot Matrix marvel at the transformation. Just as it looks like Spaceball One is successful, Lonestar uses his Schwartz training to turn the vacuum cleaner's switch into the off position. They then fly into the ear of the Mega Maid.",
					"Lonestar finally has his face to face confrontation with Dark Helmet. After a Schwartz measuring contest Dark Helmet reveals that there's two sides to every Schwartz. Lonestar, without his ring, manages to defeat Dark Helmet and push Spaceball One's self destruct button. The Spaceballs and everyone and everything inside the ship flee, that is except for Dark Helmet, Col. Sanders, and President Skroob. The ship self destructs and Mega Maid's head crash lands on an ape planet. The apes are horrified to discover that their planet is being taken over by Spaceballs. Back on the Winnebago, Lonestar and Barf learn that Pizza The Hutt has kicked the bucket and they don't owe him anything anymore.",
					"Victorious, Lonestar heads for Druidia and drops Vespa off at the castle. They resume where they left off with the Princess marrying, or attempting to marry Prince Valium. As they walk down the aisle, Vespa is stunned to learn that Lonestar didn't take the money he was offered - only enough for gas and food. Lonestar and Barf are seen at a random space gas station filling up and stopping in the coffee shop. They're horrified by the contents of \"today\'s special\" and quickly get the check and make a b-line for the door. Barf is still hungry so they take a crack at the fortune cookie that Yogurt had given them. Yogurt reveals exactly what the medallion that Lonestar wears on his neck is. It\'s a royal birth certificate. It certifies that Lonestar is the son of a king and queen, and if they hurry, Lonestar could have a princess in their future. They quickly turn around and head back for Druidia. Just as it looks like the wedding is unavoidable, when the preacher gets to the \"speak now or forever hold your peace\" part, Lonestar shows up and tells Vespa that he's a certified prince and asks her to marry him. She thinks about it, and then quickly shoves Prince Valium off to the side. They get married and sail off into deep space in the Winnebago."));
			return new VHS(tl0003, rt0003, sc0003);
			
		case 4:
			String tl0004 = "E.T. the Extra-Terrestrial";
			int rt0004 = 115;
			ArrayList<String> sc0004 = new ArrayList<>(Arrays.asList(
					"In a forested area overlooking a sprawling suburban neighborhood, an alien spacecraft has landed. The creatures aboard have come to observe and collect specimens. One of them wanders some distance away, when strange lights and sounds cause him to hide. The group of men are led by one who has a jingling set of keys attached to a belt loop. Scared, the creature takes of running, with the men in pursuit. The creature attempts to get back to his spaceship, but it leaves without him. Eventually, it makes its way down an embankment into the suburban housing development below.",
					"In one house, a young boy named Elliot is sent out to pick up a pizza being delivered for his brother Michael and his friends. Elliot is about to return inside when a strange noise in the backyard catches his ears. Elliot traces the noise to a gardening shed in the backyard. Elliot throws a baseball into the shed, and is scared when something in the shed throws it back out. Elliot rushes inside to tell everyone, and they all come out to investigate, but find nothing in the shed, except for some strange prints, which Michael assumes must belong to some type of coyote from the nearby woods.",
					"Later that evening, Elliot hears some noise outside in the backyard, and goes outside. He encounters a strange creature that scares the both of them. The creature quickly leaves the backyard and through a nearby gate that leads into the woods.",
					"The next day, Elliot goes out on his bike to the forest, taking a bag of Reese Pieces with him, hoping to find the creature he saw. He soon sees the man with the keys on his belt loop, and quickly leaves the forested area.",
					"That evening, Elliot gets into an argument with his family, when it seems that no one will believe him. Elliot claims that his Dad would believe him. As their Mother has just been through a messy divorce, this causes her feelings to be hurt, with Michael angrily chastising his brother for being cruel.",
					"Later that evening, Elliot stays outside, where this time, the creature comes right up to him, and returns some of the Reeses Pieces that were in the forest. Elliot then lures the creature into the house and up to his room. When he finally sees the creature in full, it is a strange brown-colored being that is like nothing he\'s ever seen before. The creature has a gentle nature and seems as curious about Elliott as the boy is about it.",
					"Elliot fakes having a fever the next day to stay home from school. During the day, he acclimates himself to the creature, and tells him his name, as well as shows him different things around the house. Later that evening, Elliot shows the creature to Michael and their younger sister Gertie, who both promise not to tell anyone about him.",
					"They soon surmise that this thing must in some way be an alien, and get him to try and explain where he\'s from. Instead, the creature displays its powers, which cause several spheres to levitate and rotate like the planets in the solar system. Gertie also gives the alien a potted plant with dying flowers, which the alien revives, bringing them into full bloom.",
					"Elliot has the creature hide in his closet the next day, as everyone heads off to school. While everyone is away, the alien gets out and into the fridge, raiding the food and drinking several beers, before watching TV. Unknown to Elliot, the alien has formed a mental bond with him, and these feelings carry on over to his science class, where Elliot finds himself setting loose a number of frogs for a dissection project and causing chaos. Elliott also feels a surge of emotion that prompts him to kiss a blonde girl in his class.",
					"After Elliot returns home that evening, he finds that Gertie has helped teach the alien to talk, and Elliot then decides to name the alien E.T. E.T. then attempts to explain that he intends to build a machine to communicate with his home planet, so they can come to get him.",
					"Later that evening, Elliot and Michael go through the garage looking for items to use. Michael notes that E.T. doesn\'t look so good, to which Elliot explains that \"they are fine.\" Unknown to the two of them, a van monitoring outside has picked up their conversation.",
					"On Halloween, Elliot and Michael dress E.T. up in a sheet, passing him off to their mother as Gertie dressed up as a ghost. Gertie has already left with Elliot\'s bicycle, and gone to a specific point above the suburban area. Once the three meet her there, Gertie trades places with E.T., as both Elliot and\", E.T. head off to assemble and activate the communications machine he has assembled. As they travel through the forest, with E.T. perched in a basket on the handlebars, Elliott\'s bike suddenly starts racing down a steep hill toward a cliff. Elliott panics, thinking they'll die, but the bike flies safely over the precipice, the little alien having used an unknown ability to make the bike take off and land safely. E.T assembles and activates his crude machine and it begins to send a signal out into space. Elliott is exhausted and falls asleep, with the alien watching over him.",
					"Elliot wakes up the next day in the woods, with no sign of E.T. He returns home where his Mother has been afraid something had happened to him. Elliot pleads with Michael to find E.T. Michael first goes to the forest, but eventually finds E.T., pale pink in color and barely breathing near a storm drain.",
					"Getting him home, Michael and the others show E.T. to their mother. E.T. has taken on a pasty white look, and is shallowly breathing. Elliot explains that both he and E.T. are sick and perhaps dying. Their mother panics and demands they leave E.T. and get out of the house immediately, but they are soon set upon by persons in space suits, and then government men who quickly seal off the house and set up a medical unit to examine and help Elliot and E.T.",
					"It is here that the man with the keys on his belt loop (who we will call \"Keys\") returns to the picture. Keys explains to Elliot that they have found the machine in the forest, and wants to know how to save E.T. Keys tells Elliott that he\'s had the same kind of childlike wonder about alien beings and that finding E.T. is a lifelong dream come true. Elliot weakly explains that E.T. needs to go home, but as they talk, E.T. soon detaches himself from Elliot, and finally succumbs to the illness, leaving Elliott to recover. Michael realizes this when the plants E.T. had revived begin to wilt and die.",
					"The medical team attempts to revive E.T., but he eventually dies. Before they take E.T. away, Keys allows Elliot some time alone with E.T.. Elliot then explains that E.T. must be dead, because he can\'t feel anything anymore. Elliot then tells E.T. that he loves him, and turns away. As he does so, he sees the flowers that were dying before are returning to life. Elliot goes back to the container where E.T. is, and finds him alive, and explains that his planet\'s people will be returning to get him. Elliot manages to hide the fact that E.T. is alive, and then hatches a plan with Michael to get him to the forest.",
					"Michael has his friends take Elliot's bike and theirs to a playground at the top of a nearby hill. Meanwhile, Michael and Elliot steal the van with E.T.'s container, and make their way to the playground. Meeting Michael's friends there, they then take E.T. and head for the forest. The government agents then give chase. As they race away, they see a roadblock ahead, armed agents waiting around the cars. Just as it seems they'll all be captured, E.T. levitates all the kids' bikes and they fly off toward the woods.",
					"As they land, and night settles, E.T.'s ship lands. Elliot's mother and Gertie show up shortly afterward, and Gertie and Michael say their goodbyes, before it's Elliot's turn. E.T. asks Elliot to come with him, but Elliot says he has to stay. E.T. gives his new friend a hug, and then lights his finger and points it at Elliot\'s head, telling Elliot that he\'ll \"be right here.",
					"Gertie gives E.T. the plant she initially gave him, and he goes into the enormous ship, which soon lifts off leaving a rainbow behind, as everyone stares off into the sky."));
			return new VHS(tl0004, rt0004, sc0004);
			
		case 5:
				String tl0005 = "The Terminator";
				int rt0005 = 107;
				ArrayList<String> sc0005 = new ArrayList<>(Arrays.asList(
						"Over an apocalyptic battlefield in the year 2029, the ruins of the city of Los Angeles are dominated by robotic war machines, some like tanks, others are hover-crafts, a title card tells us that in the future, humans will wage a long war against an enemy known as the Machines. The \"final battle\" however, will not be fought in this future world, but in the past, specifically our present... tonight.",
						"The year switches to Los Angeles, May 12, 1984 at 1:34 am. At the Griffith Park Observatory overlooking the city, lightning emanates from above a garbage truck, knocking out power. The driver sees a naked and heavily muscular man (Arnold Schwarzenegger). The man stands up and starts walking toward the city where he is spotted by three young punks. The man gives several indifferent answers to a series of sarcastic questions they punks ask him and then orders the men to give him their clothes. The punks produce knives in response. The man swats two punks aside, the third stabs him, but the man impossibly tears open the punk's body with his bare hands, and kills him. The third punk, seemingly the only one left alive, immediately begins to remove his coat.",
						"In a downtown alley, a homeless man sees a bright, circular light just above the ground, similar to the one at Griffith Park. A scarred, naked man, muscular but much smaller in size than the other man who arrived in a similar fashion, is forced through the portal and lands in the alley, in obvious pain. This is Kyle Reese (Michael Biehn). Reese takes the homeless man's pants, just as a police car pulls up and two cops yell at him to freeze. Reese is able to hide and attacks one of the cops, taking his pistol and demanding the cop tell him the date and year. The cop becomes puzzled by Reese's question. When the cop's partner arrives, Reese runs into a department store. He steals several items, including a pair of Nike sneakers and a long coat and escapes the store. In another alley outside, he steals a shotgun from an unoccupied squad car. Finding a phone book nearby, he looks up the name \"Sarah Connor.\"",
						"Elsewhere a young woman, Sarah Connor (Linda Hamilton), lives the life of a lonely waitress. Sharing an apartment with her friend Ginger, Sarah is living out a boring life that seems to go nowhere.",
						"The muscular man steals a car and goes to a local sporting goods store where he has the owner (Dick Miller) show him several assault weapons and a pistol with laser sighting. He flatly asks for a \"phased-plasma rifle\"; the owner tells him \"Only what you see, pal\". The owner tells his customer that he can take the rifles right away but the pistol has a waiting period. As he explains the process, the man casually loads the shotgun and shoots the clerk. Shortly after, the man finds a phone book and looks for the name \"Sarah Connor\" finding three listings in the Los Angeles area. He goes to the address of the first listing; as he walks to the front door, a small dog barks at him. When this Sarah Connor opens the door and acknowledges her name, the man forces his way inside and shoots her with the pistol he acquired. Not long after, at the diner where she works, Sarah's co-worker drags her to the television where she sees a news report about a woman sharing her name having been murdered by an unidentified assailant.",
						"That evening, Sarah and her roommate, Ginger, prepare for separate dates. Ginger's boyfriend, Matt, will be coming over to spend the night. Sarah gets a message from her date, who cancels. Sarah decides to go out for pizza and sees another news report where the police announce the death of another woman sharing her name. Sarah becomes worried, and when she sees she is being followed (by Kyle Reese), she ducks into a small dance club called Tech Noir. She tries to call Ginger, however Ginger and Matt do not hear the phone as they are having sex. Not long after Sarah's call, the killer attacks and fatally shoots Ginger and Matt, before hearing Sarah's voice on their answering machine saying where she is. Sarah then phones the police department and is connected to Lt. Traxler, the detective investigating the Sarah Connor killings. He tells Sarah to stay put until he can get a squad car to her. The killer arrives at the club, dispatches a bouncer, and wades into the crowd.",
						"In the meantime, Reese has also entered the dance club. Sarah is finally spotted by the killer, which aims its laser sighted pistol at her. Reese fires on the killer, hitting him with several blasts, knocking him to the floor. Sarah sees the killer impossibly rise to its feet and open fire on Reese with the Uzi it stole. He advances on Sarah again, shooting the woman behind her, the woman's body pinning her to the floor. As the killer advances on her and prepares to shoot her, Reese appears again and hits the killer with several more shotgun blasts, blasting him out the front window of the club where he lands on the street. He tells Sarah \"Come with me if you wanna live\" as the killer arises again and chases them out the back of the club.",
						"Reese and Sarah run through an alley behind the club as the killer chases them. From the killer's perspective we see that he is a robot of some kind who sees them through a computerized form of night vision. Reese blasts the gas tank of a nearby car which explodes. The killer is unfazed, and jumps on the hood of Reese's car, smashing its fist through the windshield and grasping at Sarah. Reese maneuvers his car in reverse and throws the killer off. Reese speeds off while the Terminator subdues a cop (screenwriter William Wisher) and takes his squad car. During the chase, the killer listens closely to the police reports on the car's radio and responds in the cop's voice.",
						"During the chase, Reese frantically identifies himself as a sergeant with a serial number and explains that Sarah has \"been targeted for termination\" and that the killer chasing them is not a man but a machine called a \"terminator\"; a metallic combat chassis covered with living human tissue to make it appear human. They race through several alleys, finally stopping in a parking garage. Reese tells Sarah that the first and larger 600 Series Terminators had rubber skin, but the newer 800 Series are very hard to identify which is why he followed Sarah and waited for the Terminator to make its move so he could identify it. Incredulous, Sarah panics and begins to scream for help, biting Reese on the hand. He tells her not to do it again.",
						"In the parking garage, they leave behind Reese's car and find another unlocked one. Reese explains further that a nuclear war will be initiated by a new, powerful computer system (referred to as \"Skynet\" in the first sequel) that is going to be tasked with controlling all defense systems. Reese himself has not seen the ensuing nuclear holocaust but was born and grew up destitute and starving in the ruins. He was enslaved and marked with a barcode and was forced to work loading bodies into incinerators. The human race, he says, will be on the verge of extinction when one man, John Conner, is able to organize the remaining humans into an effective resistance movement that, by the time Reese will be sent back to the present day by Connor himself, had actually defeated Skynet. John Conner is Sarah's future son.",
						"In desperation, Skynet has sent the Terminator to the present day to murder Sarah and eliminate John Connor's existence. Reese also explains that the Terminator pursuing Sarah, is a new model, one that appears infinitely more human than its predecessors. Reese tells her the android will bleed, sweat and even has bad breath to enhance the disguise. Reese is uncertain that he can defeat the android without having the advanced weaponry of the future.",
						"The Terminator finds them there and the chase resumes. Reese has Sarah take over driving and is able to hit the Terminator with a few blasts from his shotgun. Sarah stops their car and the Terminator crashes into a wall. As the police close in, Reese is ready to shoot at them but Sarah stops him, saying they'll kill him. When she and Reese are arrested, she sees that the Terminator has escaped the scene.",
						"At Traxler's police precinct, Sarah is told that Ginger is dead and that Reese has been given to a criminal psychiatrist, Dr. Peter Silberman (Earl Boen). His story about the Terminator is treated as the babbling of extreme delusion. While watching the videotape of the interview, Silberman eagerly says that a case like Reese's could be career-making. During the interview, Silberman asks Reese why he didn't bring weaponry from the future with him, to which Reese replies that only living material will go through the time portal. Reese quickly becomes agitated and begins to scream into the camera that the Terminator must be destroyed or it will not stop until it kills Sarah.",
						"The Terminator goes back to a shoddy hotel room where it hides out. It removes one of its eyes that had been damaged when it was shot by Reese. Under the human eye is a sophisticated robotic eye that glows red. It dons a set of sunglasses, changes into different clothes and marches out to resume the hunt for Sarah, taking a pump-action SPAS shotgun and an AR-18 automatic rifle.",
						"At the police precinct, the Terminator arrives in the foyer just as Dr. Silberman is leaving and asks to see Sarah. The desk sergeant refuses to let the Terminator in. The Terminator looks menacingly at the desk sergeant, then up and around and simply states \"I\'ll be back.\" The Terminator goes outside and one minute later crashes a car through the front door. It marches through the precinct, ruthlessly shooting every officer in its path. The Terminator gets to a circuit panel and after ripping out a main circuit cable, shoves the live wire into the fuse box creating an electrical surge that blows out all lights in the building, leaving the policemen at a disadvantage. In the battle, Traxler is hit by gunfire and Reese escapes confinement. He finds Sarah and the two escape the precinct.",
						"While hiding out in a sewer tunnel, Sarah realizes that Kyle's story is true. Reese tells her more about the future where humans barely survive amid the wreckage of cities and the predation of the Terminators. Initially, Skynet's vehicles, \"hunter-killers\" or HKs, would use infra-red technology to find and kill humans. Kyle mentions that John Connor's talent for strategy helped the Resistance to defeat them. Later, the new Terminators, \"infiltrators\" like the one he and Sarah are on the run from, appeared and began to find hidden bunkers where humans hid out. Sarah lapses into sleep and has a nightmare of a firefight where Terminators break into a human sanctuary and massacre scores of civilians. Kyle himself is there; after finding a place to rest after a Resistance patrol, he takes out a Polaroid photo of Sarah and admires it. Alerted by dogs (who can sense a Terminator) at the entrance to the bunker, Reese joins the valiant fight to destroy a Terminator that has gotten in. The Terminator, carrying a heavy plasma gun, slaughters everyone and causes an explosion that cripples Reese. Reese sees the picture of Sarah being burned nearby.",
						"Meanwhile, the Terminator is back in its seedy motel room hideout looking at an address book that it took from Sarah and Ginger's apartment and sees a list of names including that of Sarah's mother who lives upstate. After harshly dismissing the hotel owner, the Terminator then leaves its room and gets on a stolen motorcycle and takes off on the road.",
						"Later, the two reach a roadside motel, where Kyle goes to purchase chemicals needed to make explosives. While he is shopping (using \"borrowed\" money) Sarah showers and phones her mother, telling her the phone number where she is, unaware that the Terminator is on the other line and recreating the voice of Sarah's mother. Sarah's mother is nowhere in sight, but the appearance of the cabin's knocked down front door with a large shotgun blast hole in it suggests that the Terminator forced its way in and probably shot Sarah's mother and waited for Sarah to call. The Terminator then phones the motel and, using its real voice, asks the desk clerk to give him the motel's address.",
						"At the motel, Reese returns with a bag full of unusually matched items like ammonia and corn syrup. Sarah and Kyle make a stockpile of pipe bombs filled with plastique, a compound that Kyle had learned to make and teaches Sarah to make as well, also showing her the cautious process involved to make the bombs. When Sarah asks Kyle if he has ever had a lover, he replies he has not, a fact that touches Sarah. Kyle then mentions having a photo of Sarah and how he has fallen in love with her. Realizing he has gone too far, he furiously begins loading explosives, but Sarah stops him and kisses him. The two lose their inhibitions and have sex. Their consummation results in the conception of Sarah's (and Kyle's) son, John.",
						"That evening, the Terminator tracks them to the motel and the two flee again in a stolen pickup truck (alerted by a tenant's pet dog barking at the sight of the approaching Terminator). As they race down a wide highway, Reese makes a valiant effort to destroy the Terminator with the pipe bombs he and Sarah made, however, he is hit by gunfire. Sarah manages to knock the Terminator off its motorcycle and her truck flips over.",
						"The Terminator recovers and is immediately struck by a semi-tanker truck and dragged for a short distance. After the driver stops, the Terminator kills him and takes control of the truck, (ordering the truck driver's partner to \"Get out!\") attempting to run down Sarah. Sarah is able to get Kyle out of their wrecked pickup before the Terminator runs it down.",
						"Near a factory, Kyle uses another pipe bomb to detonate the truck's tank trailer, which explodes. As Reese and Sarah embrace, the Terminator emerges from the wreckage, its flesh completely burned off. Reese and Sarah retreat into the factory, which is automated. Reese switches on as many of the machines as he can, making tracking more difficult for the Terminator. They are finally cornered and Reese places his last bomb in the endoskeleton of the Terminator, which explodes, scattering pieces of the android. Sarah, nursing a severely injured leg, finds Reese, but he's dead.",
						"She is suddenly attacked by the top half of the Terminator's skeleton. She desperately crawls away, finally luring the Terminator into a giant hydraulic press. She traps it there and, as it mindlessly tries to break her neck, pushes the button activating the press. The Terminator is crushed until its red glowing eye fades.",
						"Sarah is taken to an ambulance and sees the paramedics loading Kyle into a body bag. Later, she is driving a Jeep in the desert, a large dog in the passenger seat, seemingly towards Mexico, stopping at a gas station. She is more visibly pregnant with John Connor and has been recording her voice using a cassette player; the tapes are for her son. One of the questions she poses is whether or not she should tell John about Reese being his father and if that will affect his decision to send the warrior back in time to meet and save Sarah. While the Jeep's tank is filled, a young boy takes her picture with a Polaroid camera (it is the same picture that John will give Reese in the future). She and the boy bargain over the price and she buys it. The boy says something in Spanish and the gas station owner tells her he said \"A storm's coming!\" Sarah sees the storm approaching and says \"I know.\" She drives off into an unknown future."));
				return new VHS(tl0005, rt0005, sc0005);
				
				case 6:
					String tl0006 = "Donnie Darko";
					int rt0006 = 113;
					ArrayList<String> sc0006 = new ArrayList<>(Arrays.asList(
							"Donnie Darko (Jake Gyllenhall) is a troubled teenager in suburban Maryland. A schizophrenic with a history of violence, he has recently stopped taking his medication and as a result is sleepwalking. His parents, Rose and Eddie (Mary McDonnell and Holmes Osborne) and his sisters, Elizabeth and Samantha (Maggie Gyllenhall and Daveigh Chase), worry about him. One night at dinner, Donnie and his sister get into a profane argument during which Elizabeth reveals she knows Donnie is no longer taking his medication. Rose confronts Donnie in his bedroom and he calls her a bitch. Guilty, Donnie resumes taking his medication. On October 2nd, however, he sleepwalks and meets Frank, a man in a menacing bunny costume. Frank tells him that in 28 days, 6 hours, 42 minutes and12 seconds, the world will end. That night, a jet engine mysteriously crashes through the roof of the Darkos\' house, destroying Donnie\'s room. Had he not been sleepwalking, he would have been killed.",
							"On the way to the office of Dr. Thurman (Katherine Ross), Donnie's therapist, Donnie and Eddie nearly run over Roberta Sparrow, also known as \"Grandma Death\" (Patience Cleveland). A senile old woman who spends her days walking back and forth from her house to the mailbox across the street, Grandma Death whispers in Donnie\'s ear that all that lives ultimately dies alone. This greatly troubles Donnie, who worries that life has no meaning.",
							"A few days later, Frank appears to Donnie in a hallucination and encourages him to flood the private high school he attends by breaking open the water main with an ax. Donnie also embeds the ax in the head of the school\'s solid bronze statue of its mascot and spraypaints \"They made me do it\" on the sidewalk. School is canceled that day and Donnie walks home Gretchen (Jena Malone), the new girl in school. She reveals that her stepfather nearly killed her mother and is still on the loose. Donnie reveals his own troubled past as well as his intelligence. Gretchen decides that Donnie is weird and that this makes him attractive. They agree to become a couple.",
							"Donnie has a troubled relationship with the faculty at his high school. Ms. Pomeroy (Drew Barrymore) appreciates his intellect and ability to engage with and understand the difficult material she assigns them to read in English class. The science teacher, Mr. Monnitoff (Noah Wyle), finds him a little more troubling, and Kitty Farmer (Beth Grant), the high strung and socially conservative health instructor, is offended that he questions her use of self-help tapes in class. After he profanely rejects her use of the simplistic methods espoused by local celebrity Jim Cunningham (Patrick Swayze), Donnie finds himself suspended from afterschool activities. When Donnie verbally assaults Cunningham during an appearance at the high school, he gets in even deeper trouble. Although the administration suspects that Donnie is indeed responsible for the vandalism, he is never charged.",
							"Frank continues to appear to Donnie and tells Donnie that they can do anything and won't get caught. Frank also tells Donnie about time travel, further confusing him. Soon, Donnie sees tubes of fluid light extending out of his family\'s chests, indicating where they will go. His own tube beckons him to follow as it enters his parents\' room and reveals the gun his father keeps in a box in the closet. Donnie speaks about time travel with Mr. Monnitoff who gives him a book, The Philosophy of Time Travel written by Roberta Sparrow. She used to be a nun and a teacher at the high school. However, the climate at the school is becoming increasingly conservative as Kitty Farmer leads a protest against Ms. Pomeroy\'s choice of reading material; one of the stories she had assigned, Graham Greene\'s The Destructors features teenagers who destroy a man\'s house by flooding it. Ms. Pomeroy is fired and Mr. Monnittoff, who is also her boyfriend, refuses to discuss time travel with Donnie once his questions take a theological direction.",
							"Gretchen and Donnie grow closer. She is one of the few people he opens up to about his time travel visions, and they discuss how they wish they could travel back in time and prevent the bad things in their lives from happening. Dr. Thurman increases Donnie\'s medication and begins hypnotherapy with him. But Frank continues to appear to Donnie. One night, Donnie and Gretchen go to see a horror movie. Gretchen falls asleep and Frank appears. When Donnie asks Frank to remove his bunny suit, Frank asks Donnie to remove his human suit, then acquiesces and takes the head off, revealing a young adult with a gruesome wound in his right eye. When Donnie asks about the cause of the eye wound, Frank whispers \"I am so sorry\" and then directs Donnie\'s attention to the movie screen. A portal opens, revealing Jim Cunningham\'s house. Frank tells Donnie to burn it to the ground. Donnie leaves the sleeping Gretchen in the theatre and does as Frank tells him to. He is not caught, and firefighters discover a kiddie porn dungeon in a hidden room in the mansion. Cunningham is arrested the next morning. Kitty Farmer, a friend and devoted follower of Cunningham\'s, decides she must lead his public defense and asks Rose to accompany the school\'s dance team, Sparkle Motion, to Los Angeles to appear on Star Search. Samantha is Sparkle Motion\'s lead dancer and, against her better judgment, Rose agrees. Because Eddie is away on business, this means Elizabeth and Donnie are on their own.",
							"Elizabeth is accepted into Harvard, and she and Donnie decide to throw a Halloween party to celebrate. The night of the party (October 30), Gretchen comes to Donnie\'s house for safety because her mother has suddenly disappeared. Donnie comforts her and they make love, ignoring phone calls from Donnie\'s desperate therapist (who knows that Donnie is responsible for the vandalism to the high school and Jim Cunningham\'s house) and Rose, who calls to announce that Sparkle Motion won their initial Star Search competition and that they will return on a red eye flight that night.",
							"At midnight, Donnie has another hallucination about the fluid light tunnels. He realizes that the 28 days have passed, and that only 6 hours remain until the end of the world. Convinced that Grandma Death is in some way connected to Frank, Donnie persuades Gretchen and two other friends to go with him to her house. When they get there, they are assaulted by the high school\'s resident bullies (Alex Greenwald and Seth Rogen). Gretchen is thrown dazed into the road, where she is struck and killed by a car driven by Frank (James Duval), Elizabeth\'s boyfriend who is on his way to their Halloween party. Frank is wearing the creepy bunny costume that Donnie\'s hallucination wears. Donnie uses his father\'s gun to shoot Frank in the right eye, killing him, then carries Gretchen\'s body to his home. He steals the car keys from a sleeping Elizabeth and, taking Gretchen with him, drives into the hills above town.",
							"From that vantage point, Donnie can see a time tunnel forming over the town. The red eye flight carrying Rose and Sparkle Motion enters the turbulence created by the time tunnel, and one of the engines on the jet breaks free and falls into the tunnel. Donnie looks at Gretchen with love and then drives into the time tunnel.",
							"It is October 2. Donnie lies in bed, laughing, happy. Shortly after he goes to sleep, the jet engine from the red eye flight on October 30 crashes through the roof, killing him. Throughout town, Dr. Thurman, Mr. Monnitoff, Kitty Farmer, Jim Cunningham and Frank all are suddenly troubled and sad. The next morning, Gretchen rides her bike to the Darkos\' house. Elizabeth, Eddie and Samantha stand sobbing as Donnie\'s corpse is taken away, while Rose smokes a cigarette a few feet away, doing her best to deal with the fact that her last encounter with her troubled son was the unpleasant confrontation in his bedroom. Gretchen finds out from a young boy what had happened and who the family is, as she had never met Donnie. Touched by the tragedy, she shyly waves to Rose. Touched by a stranger\'s act of kindness, Rose waves back."));
					return new DVD(tl0006, rt0006, sc0006);
		}
		
		return null;
	}
}
